/****** Object:  View [dbo].[vw_purchase_orders]    Script Date: 25/10/2025 11:08:57 ã ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







ALTER VIEW [dbo].[vw_purchase_orders]
AS
With tb as
(
	SELECT FILE7_20H.ORDER_NO,		
		   FILE7_20.ITEM,
		   FILE7_20.QUANT AS QUANT_PUR,
		   0 AS QUANT_ORDER,
		   0 AS QUANT_RCV,
		   0 AS QUANT_TRANS,
		   FILE7_20.TOTAL AS TOTAL_PURCHASE,
		   0 AS TOTAL_ORDER,
		   0 AS TOTAL_TRANS
		FROM FILE7_20H 
		INNER JOIN FILE7_20 ON FILE7_20H.DOC_NO = FILE7_20.DOC_NO
		WHERE ORDER_NO IS NOT NULL
	UNION ALL
	SELECT FR7_20H.ORDER_NO,		
		   FR7_20.ITEM,
		   FR7_20.QUANT AS QUANT_PUR,
		   0 AS QUANT_ORDER,
		   0 AS QUANT_RCV,
		   0 AS QUANT_TRANS,
		   FR7_20.TOTAL AS TOTAL_PURCHASE,
		   0 AS TOTAL_ORDER,
		   0 AS TOTAL_TRANS
	FROM FR7_20H 
		INNER JOIN FR7_20 ON FR7_20H.DOC_NO = FR7_20.DOC_NO
		WHERE ORDER_NO IS NOT NULL
	
	UNION ALL
	SELECT FILE1_60H.DOC_ORDER,		
		   FILE1_60.ITEM,
		   0 AS QUANT_PUR,
		   0 AS QUANT_ORDER,
		   0 AS QUANT_RCV,
		   FILE1_60.QUANT AS QUANT_TRANS,
		   0 AS TOTAL_PURCHASE,
		   0 AS TOTAL_ORDER,
		   FILE1_60.QUANT * FILE1_60.COST AS TOTAL_TRANS
	FROM FILE1_60H
		INNER JOIN FILE1_60 ON FILE1_60.DOC_NO = FILE1_60H.DOC_NO
		WHERE FILE1_60H.DOC_ORDER IS NOT NULL
	
	UNION ALL
	SELECT FILE6_50.DOC_NO,
		   FILE6_50.ITEM,
		   0 AS QUANT_PUR,
		   QUANT AS QUANT_ORDER,
		   0 AS QUANT_RCV,
		   0 AS QUANT_TRANS,
		   0 AS TOTAL_PURCHASE,
		   FILE6_50.TOTAL AS TOTAL_ORDER,
		   0 AS TOTAL_TRANS
	FROM FILE6_50
		INNER JOIN FILE6_50H ON FILE6_50H.DOC_NO = FILE6_50.DOC_NO
	
	UNION ALL
		SELECT FILE6_55H.ORDER_NO,
		   FILE6_55.ITEM,
		   0 AS QUANT_PUR,
		   0 AS QUANT_ORDER,
		   QUANT AS QUANT_RCV,
		   0 AS QUANT_TRANS,
		   0 AS TOTAL_PURCHASE,
		   0 AS TOTAL_ORDER,
		   0 AS TOTAL_TRANS
	FROM FILE6_55
		INNER JOIN FILE6_55H ON FILE6_55H.DOC_NO = FILE6_55.DOC_NO
		WHERE ORDER_NO IS NOT NULL
)
SELECT tb.ORDER_NO,		
		tb.ITEM,
		SUM(tb.QUANT_ORDER) AS QUANT_ORDER,
		SUM(tb.QUANT_PUR) AS QUANT_PUR,
		SUM(tb.QUANT_TRANS) AS QUANT_TRANS,
		SUM(tb.total_order) as TOTAL_ORDER,
		SUM(tb.TOTAL_PURCHASE) as TOTAL_PURCHASE,
		CASE WHEN SUM(tb.QUANT_pur) + SUM(QUANT_TRANS) >  SUM(tb.QUANT_ORDER) 
			THEN SUM(tb.QUANT_ORDER) 				
		ELSE 
			SUM(tb.QUANT_PUR) + SUM(QUANT_TRANS)
		END AS QUANT_PUR_ORDER,
		CASE WHEN SUM(tb.QUANT_pur) + SUM(QUANT_TRANS) >  SUM(tb.QUANT_ORDER) 
			THEN SUM(tb.QUANT_pur) + SUM(QUANT_TRANS)- SUM(tb.QUANT_ORDER) 
		ELSE 
			0 
		END AS QUANT_OVER,
		SUM(tb.QUANT_RCV) AS QUANT_RCV
FROM tb
	GROUP BY tb.ORDER_NO,		
			 tb.ITEM


GO


