/****** Object:  StoredProcedure [rp].[sp_pur_demand_items]    Script Date: 25/10/2025 10:51:27 ã ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






ALTER PROCEDURE [rp].[sp_pur_demand_items]
@DATE1 DATETIME = NULL,
@DATE2 DATETIME = NULL,
@MOSM NVARCHAR(3) = NULL,
@SUP nvarchar(3) = NULL,
@ORDER_NO varchar(12) = NULL,
@STORE nvarchar(3) = NULL,
@SECTION INT = NULL ,
@ISEND_ORDER BIT = NULL,
@USERCODE INT = NULL,
@ISBRANCH BIT = NULL,
@ISSTOP BIT = NULL
AS
SELECT STORE_BR.DESCA AS STORE_NAME, 
	FILE4_10.DESCA,
	FORMAT(FILE6_50H.[DATE],'yyyy/M/d'),
	FILE6_50H.DOC_NO,
	FILE1_10.MODELFACT0,
	FILE1_10.DESCA,
	FILE1_10.SCAL,
	FILE1_10.ITEM,
	COUNT(DISTINCT CASE WHEN QUANT_ORDER > 0 THEN  FILE1_10.MODEL END) AS MODEL_COUNT,
	SUM(v.QUANT_ORDER) AS DEMAND,
	SUM(V.TOTAL_ORDER) AS TOTAL_ORDER,
	SUM(v.QUANT_RCV) AS QUANT_RCV,
	SUM(V.QUANT_ORDER) - SUM(V.QUANT_RCV) AS QUANT_RCV_REST,
	SUM(V.QUANT_PUR) AS QUANT_PUR,
	SUM(V.QUANT_TRANS) AS QUANT_TRANS,

	SUM(V.QUANT_PUR_ORDER) AS QUANT_DONE,
	CASE WHEN SUM(V.QUANT_PUR) + SUM(V.QUANT_TRANS) > SUM(v.QUANT_ORDER)  THEN 
		 SUM(V.QUANT_PUR) + SUM(V.QUANT_TRANS) - SUM(v.QUANT_ORDER)
	ELSE		 
		 0
	END AS OVER_ORDER,
	CASE WHEN SUM(v.QUANT_ORDER) > SUM(V.QUANT_PUR_ORDER)  THEN 
		SUM(v.QUANT_ORDER) - SUM(V.QUANT_PUR_ORDER)
	ELSE
		0
	END
	AS REST_ORDER,
	(SELECT format(MAX(DATE),'yyyy/M/d') FROM FILE7_20H WHERE FILE7_20H.ORDER_NO = FILE6_50H.DOC_NO) AS LAST_DATE,
	FILE6_50H.ISEND_ORDER,
	CASE WHEN SUM(v.QUANT_ORDER) <> 0 THEN
		ROUND(SUM(v.QUANT_PUR_ORDER)/SUM(v.QUANT_ORDER),4)
	ELSE
		0
	END,
	FILE6_50H.REMARK
	FROM FILE6_50H 
		INNER JOIN vw_purchase_orders as v ON FILE6_50H.DOC_NO = v.ORDER_NO
		INNER JOIN FILE1_10 ON v.ITEM = FILE1_10.ITEM
		INNER JOIN FILE4_10 ON FILE6_50H.CODE = FILE4_10.CODE
		INNER JOIN STORE_BR ON FILE6_50H.STORE = STORE_BR.CODE
	WHERE (@DATE1 IS NULL OR FILE6_50H.[DATE] >= @DATE1)
	AND (@DATE2 IS NULL OR FILE6_50H.[DATE] <= @DATE2)
	AND (@ORDER_NO IS NULL OR FILE6_50H.DOC_NO = @ORDER_NO)
	AND (@STORE IS NULL OR FILE6_50H.STORE = @STORE)
	AND (@SUP IS NULL OR FILE6_50H.CODE = @SUP)
	AND (@SECTION IS NULL OR  FILE1_10.SECTION = @SECTION)
	AND (@MOSM IS NULL OR FILE1_10.MOSM = @MOSM)
	AND (@USERCODE IS NULL OR  FILE6_50H.[store] IN (SELECT STORE FROM USERSHOP WHERE CODE = @USERCODE))
	AND (@ISBRANCH IS NULL OR STORE_BR.S_BRANCH = @ISBRANCH)
	AND (@ISSTOP IS NULL OR STORE_BR.ISSTOP = @ISSTOP)
	AND (@ISEND_ORDER IS NULL OR FILE6_50H.ISEND_ORDER = @ISEND_ORDER)
	GROUP BY  STORE_BR.DESCA, 
	FILE4_10.DESCA,
	FILE6_50H.[DATE],
	FILE6_50H.DOC_NO,
	FILE6_50H.ISEND_ORDER,
	FILE6_50H.REMARK,
	FILE1_10.MODEL,
	FILE1_10.MODELFACT0,
	FILE1_10.DESCA,
	FILE1_10.SCAL,
	FILE1_10.C_SCAL,
	FILE1_10.ITEM
	ORDER BY 
	STORE_BR.DESCA, 
	FILE4_10.DESCA,
	FILE6_50H.[DATE],
	FILE6_50H.DOC_NO,
	FILE1_10.MODEL,
	FILE1_10.C_SCAL
GO


