/****** Object:  View [dbo].[Q_VISA_DOC]    Script Date: 30/12/2023 06:24:50 „ ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER  VIEW [dbo].[Q_VISA_DOC] AS  




SELECT        VISA.CODE, FILE6_20H.date, FILE6_20H.DOC_NO, '„»Ì⁄«  ›Ì“« ' AS DESCA, FILE6_20H.STORE, FILE6_20H.BOX, FILE6_20H.VISA, (CASE WHEN (FILE6_20H.date < CONVERT(DATETIME, '2020-03-23 00:00:00', 102) OR
                         FILE6_20H.date > CONVERT(DATETIME, '2020-09-15 00:00:00', 102)) THEN (FILE6_20H.VISA * VISA.rate) ELSE 0 END) AS Comm_Visa, CASH, (CASH + VISA + LATE + POINT) AS TSALES, DOC_NO2, PHONE, PAY, rest, 
                         FILE6_20H.VISA2, 0 AS POINT
FROM            FILE6_20H INNER JOIN
                         VISA ON FILE6_20H.CODEVISA = VISA.CODE
WHERE        (FILE6_20H.VISA > 0) AND (FILE6_20H.TYPEVISA = 0) OR
                         (FILE6_20H.VISA <> 0) AND (FILE6_20H.VISA > 0) AND (FILE6_20H.CODEVISA <> '14' AND FILE6_20H.CODEVISA <> '16')

UNION ALL
SELECT        VISA.CODE, FILE6_20H.date, FILE6_20H.DOC_NO, '„»Ì⁄«  ›Ì“« «Â·Ï ', FILE6_20H.STORE, FILE6_20H.BOX, (FILE6_20H.VISA), (CASE WHEN (FILE6_20H.date < CONVERT(DATETIME, '2020-03-24 00:00:00', 102) OR
                         FILE6_20H.date > CONVERT(DATETIME, '2020-09-15 00:00:00', 102)) THEN (FILE6_20H.VISA * visa.rate2) ELSE 0 END), CASH, (CASH + VISA + LATE + POINT) AS TSALES, DOC_NO2, PHONE, PAY, rest, FILE6_20H.VISA2, 
                         0 AS POINT
FROM            FILE6_20H INNER JOIN
                         VISA ON FILE6_20H.CODEVISA = VISA.CODE
WHERE        (FILE6_20H.VISA <> 0) AND FILE6_20H.VISA > 0 AND file6_20h.typevisa = 1 AND CODEVISA = '14'
UNION ALL
SELECT        VISA.CODE, FILE6_20H.date, FILE6_20H.DOC_NO, ' „»Ì⁄«   ›Ì“« «Â·Ï  ﬁ”Ìÿ 6 ‘ÂÊ—', STORE, BOX, (FILE6_20H.VISA), (FILE6_20H.VISA * visa.rate6), CASH, (CASH + VISA + LATE + POINT) AS TSALES, DOC_NO2, PHONE, PAY, rest, 
                         FILE6_20H.VISA2, 0 AS POINT
FROM            FILE6_20H INNER JOIN
                         VISA ON FILE6_20H.CODEVISA = VISA.CODE
WHERE        (FILE6_20H.VISA <> 0) AND FILE6_20H.VISA > 0 AND file6_20h.typevisa = 2 AND CODEVISA = '14'
UNION ALL
SELECT        VISA.CODE, FILE6_20H.date, DOC_NO, ' „»Ì⁄«   ›Ì“« «Â·Ï  ﬁ”Ìÿ > 6 ‘ÂÊ—', STORE, BOX, (FILE6_20H.VISA), (FILE6_20H.VISA * visa.rate18), CASH, (CASH + VISA + LATE + POINT) AS TSALES, DOC_NO2, PHONE, PAY, rest, 
                         FILE6_20H.VISA2, 0 AS POINT
FROM            FILE6_20H INNER JOIN
                         VISA ON FILE6_20H.CODEVISA = VISA.CODE
WHERE        (FILE6_20H.VISA <> 0) AND FILE6_20H.VISA > 0 AND file6_20h.typevisa = 3 AND CODEVISA = '14'
UNION ALL
SELECT        VISA.CODE, FILE6_20H.date, DOC_NO, ' »œ· ‰ﬁ«ÿ ', STORE, BOX, 0, (POINT * visa.reatpoint), CASH, (CASH + VISA + LATE + POINT) AS TSALES, DOC_NO2, PHONE, PAY, rest, 0, POINT
FROM            FILE6_20H INNER JOIN
                         VISA ON FILE6_20H.CODEVISA = VISA.CODE
WHERE        CODEVISA = '14' AND FILE6_20H.POINT <> 0
UNION ALL
SELECT        VISA.CODE, FILE6_20H.date, DOC_NO, '„— Ã⁄ ›Ì“« ', STORE, BOX, (FILE6_20H.VISA), CASE WHEN TYPEVISA = 0 THEN (CASE WHEN (FILE6_20H.date >= CONVERT(DATETIME, '2022-06-26 00:00:00', 102)) 
                         THEN (FILE6_20H.VISA * visa.rate) ELSE 0 END) ELSE (CASE WHEN (FILE6_20H.date >= CONVERT(DATETIME, '2022-06-26 00:00:00', 102)) THEN (FILE6_20H.VISA * visa.rate2) ELSE 0 END) END, CASH, 
                         (CASH + VISA + LATE + POINT) AS TSALES, DOC_NO2, PHONE, PAY, rest, FILE6_20H.VISA2, 0
FROM            FILE6_20H INNER JOIN
                         VISA ON FILE6_20H.CODEVISA = VISA.CODE
WHERE        FILE6_20H.VISA < 0 AND FILE6_20H.CODEVISA <> '16'


UNION ALL
SELECT        VISA.CODE, FILE6_20H.date, DOC_NO, '„»Ì⁄«  ›Ì“«  WIFI', STORE, BOX, (FILE6_20H.VISA+FILE6_20H.VISA3), 0, CASH, (CASH + VISA +VISA3+ LATE + POINT) AS TSALES, DOC_NO2, PHONE, PAY, rest, FILE6_20H.VISA2, 0
FROM            FILE6_20H INNER JOIN
                         VISA ON FILE6_20H.CODEVISA = VISA.CODE INNER JOIN
                         FILE0_40 ON FILE6_20H.store = FILE0_40.CODE
WHERE        (FILE6_20H.VISA +VISA3<> 0) AND file6_20h.typevisa = 4 AND FILE6_20H.CODEVISA <> '17'

UNION ALL
SELECT        VISA.CODE, FILE6_20H.date, DOC_NO, 'CIB „»Ì⁄«  ›Ì“« €Ì— ', STORE, BOX, (FILE6_20H.VISA+VISA3) AS Expr3, (FILE6_20H.VISA * VISA.rate)+(FILE6_20H.VISA3 * VISA.rate)  AS Expr5, CASH, (CASH + VISA +VISA3+ LATE + POINT) AS TSALES, DOC_NO2, PHONE, PAY, rest, 
                         FILE6_20H.VISA2, 0
FROM            FILE6_20H INNER JOIN
                         VISA ON FILE6_20H.CODEVISA = VISA.CODE
WHERE        (FILE6_20H.VISA +VISA3<> 0) AND (FILE6_20H.TYPEVISA = 5 OR FILE6_20H.TYPEVISA3 = 5) AND (FILE6_20H.CODEVISA = '16'OR  FILE6_20H.CODEVISA3 = '16')

UNION ALL

SELECT        VISA.CODE, FILE6_20H.date, DOC_NO, 'CIB „»Ì⁄«  ›Ì“« „Ì“… ', STORE, BOX, (FILE6_20H.VISA+VISA3) AS Expr3, ((FILE6_20H.VISA + VISA3 )* VISA.rate3) AS Expr5, CASH, (CASH + VISA +VISA3+ LATE + POINT) AS TSALES, DOC_NO2, PHONE, PAY, rest, 
                         FILE6_20H.VISA2, 0
FROM            FILE6_20H INNER JOIN
                         VISA ON FILE6_20H.CODEVISA = VISA.CODE
WHERE        (FILE6_20H.VISA + VISA3 <> 0) AND (FILE6_20H.TYPEVISA = 8 OR FILE6_20H.TYPEVISA3 = 8  ) AND (FILE6_20H.CODEVISA = '16' OR FILE6_20H.CODEVISA3 = '16')


UNION ALL
SELECT        VISA.CODE, FILE6_20H.date, DOC_NO, 'CIB „»Ì⁄«  ›Ì“«  ', STORE, BOX, (FILE6_20H.VISA+VISA3) AS Expr3, ((FILE6_20H.VISA +VISA3)* VISA.rate2) AS Expr5, CASH, (CASH + VISA +VISA3+ LATE + POINT) AS TSALES, DOC_NO2, PHONE, PAY, rest, 
                         FILE6_20H.VISA2, POINT
FROM            FILE6_20H INNER JOIN
                         VISA ON FILE6_20H.CODEVISA = VISA.CODE
WHERE        (FILE6_20H.VISA +VISA3<> 0) AND (FILE6_20H.TYPEVISA =  6 OR FILE6_20H.TYPEVISA =  6 ) AND (FILE6_20H.CODEVISA = '16' OR  FILE6_20H.CODEVISA3 = '16')





GO


