ALTER TABLE [dbo].[FILE6_20H] ADD [UUID_RC] varchar(256) COLLATE Arabic_CI_AS  NULL
GO

ALTER TABLE [dbo].[FILE6_20H] ADD [PREVIOUS_UUID] varchar(265) COLLATE Arabic_CI_AS  NULL
GO

ALTER TABLE [dbo].[FILE6_20H] ADD [POS_SERIAL] nvarchar(50) COLLATE Arabic_CI_AS  NULL
GO

ALTER TABLE [dbo].[FILE6_20H] ADD [DATE_QR] datetime  NULL
GO

ALTER TABLE [dbo].[FILE6_20H] ADD [UUID_RC_PREVIOUS] varchar(265) COLLATE Arabic_CI_AS  NULL
GO

