CREATE TABLE [dbo].[FILE6_20R] (
  [DOC_NO] varchar(12) COLLATE Arabic_CI_AS  NOT NULL,
  [RESPONSE] nvarchar(max) COLLATE Arabic_CI_AS  NULL,
  [SUCCESS] bit  NULL,
  [UUID] nvarchar(300) COLLATE Arabic_CI_AS  NULL,
  [PREVIOUS_UUID] nvarchar(300) COLLATE Arabic_CI_AS  NULL,
  [DATE_SEND] datetime  NULL,
  [DATE] datetime  NULL,
  [ERROR] nvarchar(max) COLLATE Arabic_CI_AS  NULL,
  [Document_Body] nvarchar(max) COLLATE Arabic_CI_AS  NULL,
  [StatusCode] int  NULL,
  [ID] int  IDENTITY(1,1) NOT NULL,
  CONSTRAINT [PK_FILE6_20R] PRIMARY KEY CLUSTERED ([ID])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE FUNCTION [dbo].[GetPreviousUUID]
(
	@DOC_NO VARCHAR(12)
)
RETURNS NVARCHAR(500)
AS
BEGIN
	-- Declare the return variable here
	DECLARE @RETURN NVARCHAR(500)

	SELECT TOP 1 @RETURN = FILE6_20H.UUID_RC
	FROM FILE6_20H LEFT JOIN FILE6_20H AS FILE6_20H_P
	ON FILE6_20H.UUID_RC = FILE6_20H_P.PREVIOUS_UUID
	WHERE (NOT FILE6_20H.UUID_RC IS NULL)
	AND FILE6_20H_P.DOC_NO IS NULL
	AND FILE6_20H.DOC_NO <> @DOC_NO
	ORDER BY FILE6_20H.DOC_NO

	RETURN @RETURN
END